# Generated by Django 5.0.2 on 2024-02-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_and_authors', '0002_alter_authors_born_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='born_date',
            field=models.DateField(),
        ),
    ]
