# Generated by Django 5.0.2 on 2024-02-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_and_authors', '0003_alter_authors_born_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
