# Generated by Django 5.0.2 on 2024-02-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_and_authors', '0004_alter_authors_fullname_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='born_location',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='authors',
            name='fullname',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(),
        ),
    ]
